version: "3"
services:
  db:
    container_name: mysql_cats
    restart: on-failure
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cats
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/preferKim/docker/data:/var/lib/mysql