version: '3'
services:
  db:
    container_name: cat
    image: mysql
    environment:
      MYSQL_DATABASE: ${SPRING_DATASOURCE_URL}
      MYSQL_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - Users/user/data:/var/lib/mysql
    restart: no