version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - my-net
  app:
    container_name: cat_picture_search
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure
networks:
  my-net:
    driver: bridge