version: "3"
services:
  db:
    image: mysql:8.0
    restart: no
    container_name: cat_picture_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cat_picture
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/ysk/Develop/data:/var/lib/mysql