spring:
  profiles:
    include:
      - api-key
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

logging:
  level:
    com.search.cat_picture.global.openFeign: DEBUG