version: "3"

services:
  db:
    container_name: cps-db
    image: mysql:8.0
    env_file:
      - ../env/db.env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always